---
title: "Resume"
format: html
---


You can [download my resume here](https://docs.google.com/document/d/1FzZsCn6kl6TQK85psxVFyFQZIj9SGp1R/edit?rtpof=true#heading=h.gjdgxs).

---

## Summary
- 8+ years of experience leading social media and digital marketing strategy across global brands including Niagara Bottling, Monster Energy, Hyatt, and NextShark

- Grew Niagara Bottling’s social audience by 150% and increased engagement by 1500% in under a year, while cutting paid ad spend by 50%

- Oversaw full-funnel campaigns at Monster Energy, blending online and offline tactics to strengthen brand presence and drive real-time community engagement

- Managed cross-functional marketing across multiple Hyatt hotels, each generating ~$15M annually, and executed campaigns for large-scale events like the Long Beach Grand Prix

- Directed creative and growth strategy at NextShark, scaling organic reach to 20M+ monthly viewers and evolving the brand into a major voice in Asian American media

- Negotiated key partnerships, including a $250K collaboration with Bumble, to expand brand visibility at Pollen

- Skilled in data-driven strategy, agency management, brand storytelling, and influencer/partnership development

- Passionate about building authentic, results-driven content that connects culture, community, and brand purpose


*For full details, view the downloadable resume or connect with me on [LinkedIn](https://www.linkedin.com/in/amao).*