project:
  type: website

website:
  title: "Mao, Andrew M12-Reflection Essay-Adv Program in R."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

